export default [
    { 
        id: 1, 
        label: 'AC', 
        triple: true, 
        double: false,
        operation: false,
    },
    { 
        id: 2, 
        label: '/', 
        triple: false, 
        double: false,
        operation: true,
    },
    { 
        id: 3, 
        label: '7', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 4, 
        label: '8', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 5, 
        label: '9', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 6, 
        label: '*', 
        triple: false, 
        double: false,
        operation: true,
    },
    { 
        id: 7, 
        label: '4', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 8, 
        label: '5', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 9, 
        label: '6', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 10, 
        label: '-', 
        triple: false, 
        double: false,
        operation: true,
    },
    { 
        id: 11, 
        label: '1', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 12, 
        label: '2', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 13, 
        label: '3', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 14, 
        label: '+', 
        triple: false, 
        double: false,
        operation: true,
    },
    { 
        id: 15, 
        label: '0', 
        triple: false, 
        double: true,
        operation: false,
    },
    { 
        id: 16, 
        label: '.', 
        triple: false, 
        double: false,
        operation: false,
    },
    { 
        id: 17, 
        label: '=', 
        triple: false, 
        double: false,
        operation: true,
    },
];
